-- Password reset links. A link carries a random token; only its SHA-256 hash is
-- stored. Single-use (used_at), time-limited (expires_at). `via` records whether it
-- was emailed to the user or generated by the operator. Not tenant data (like
-- users and sessions), so there's no book_id or row-level security.
CREATE TABLE IF NOT EXISTS password_resets (
  id         SERIAL PRIMARY KEY,
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  via        TEXT NOT NULL CHECK (via IN ('email', 'admin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at TIMESTAMPTZ NOT NULL,
  used_at    TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_password_resets_user ON password_resets(user_id);
